grammar expr;
prog: type 'main' '(' ')' '{' pr '}' ;
type : INT # typefct ;
function : ID # nomfct;
pr : ret expr ';' # instruction ;
expr : NBR # nombre ;
INT : 'int' ;
NBR : [0-9]+ ;
ret : 'return' ;
ID : [a-z]+ ;
WS : [ \t\r\n] -> skip ;
